### PR TITLE
Fix Save & Close button action

### PR DESCRIPTION
**Pull request by mjauvin**
Save & Close button action did not actually close the window in Redirects controller update action.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@bennothommo any idea what's up with the testing suite?

**Comment by bennothommo** [comment]
Not sure - I tried to replicate locally but appears to work fine. It could possibly be that it's trying to use a MySQL connection - the PHP environment is not set up for that, only SQLite.

**Comment by LukeTowers** [comment]
@bennothommo running locally on the latest develop branch commit with `artisan winter:test -p Winter.Redirect` exhibits the same behaviour for me as the github action; i.e. failing. Are you able to take another look?

**Comment by bennothommo** [comment]
@LukeTowers @mjauvin I've been able to replicate it now. Pushed a fix to Winter develop.

**Pull request merged**
